### ISSUE TITLE
Access List not work

### ISSUE THREAD

**Issue by JarrigeCedric** [openappsec/open-appsec-npm#26]
I want to restrict access to one proxy host using AccessList by Ip Range (ex : 172.22.0.0/16) and Auth Basic.   It works on NPM, but not with Open Appsec NPM. My conf is with Satify Any but still not working on Satisfy All.

Someone can help me ?

**Comment by orianelou** [comment]
Hi @JarrigeCedric, 

Thank you for reporting this, we'll look into this.

**Comment by colonelmattyman** [comment]
I'm also having this issue.

**Comment by orianelou** [comment]
Hi @stathismes and @colonelmattyman, 

Issue is fixed, please use our latest version (1.1.20).

Best,

The open-appsec team

**Comment by colonelmattyman** [comment]
I have updated to this version and it is still not working.
The site works with Basic Auth disabled, but as soon as it is enabled it says 403 Forbidden.
